### ISSUE TITLE
部署到微信小游戏，运行后报错：Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by sunkant** [potato47/so-many-games#1]

**Comment by sunkant** [comment]
菜单能够正常显示，但点击一个游戏后，就出错：

Console:

```
gameThirdScriptError

Cannot read property 'querySelector' of null
TypeError: Cannot read property 'querySelector' of null
    at t.setLoadingDisplay (http://127.0.0.1:53114/game/src/project.67404.js:1:27141)
    at t.loadSceneWithProgress (http://127.0.0.1:53114/game/src/project.67404.js:1:27454)
    at t.enterBrick (http://127.0.0.1:53114/game/src/project.67404.js:1:26929)
    at e.onBtnBrick (http://127.0.0.1:53114/game/src/project.67404.js:1:28935)
    at C.r.emit (http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:239234)
    at Function.emitEvents (http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:238918)
    at Object._onTouchEnded (http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:230923)
    at a.173.l.invoke (http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:524562)
    at http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:151077
    at Object.dispatchEvent (http://127.0.0.1:53114/game/cocos2d-js-min.8d016.js:1:151342)
console.error
errorReport @ WAGame.js:1
thirdErrorReport @ WAGame.js:1
(anonymous) @ WAGame.js:1
(anonymous) @ WAGame.js:1
(anonymous) @ WAGame.js:1
e @ gamePage.html:1
window.onerror
```
